### ISSUE TITLE
overwriting LICENSE silently

### ISSUE THREAD

**Issue by yu-ichiro** [azu/license-generator#12]
I wanted to generate a license text that I can copy/paste to other place, but I accidentally overwrote the LICENSE file of the project where I was in. Maybe just printing the output to stdout might be sufficient?

**Comment by azu** [comment]
>  Maybe just printing the output to stdout might be sufficient?
https://github.com/azu/license-generator/blob/74862699c7d7fa94b908126a724bab44ca72fbdf/src/main.rs#L54-L57

Make `write_license` optional and it can be realized, but I do not know a suitable CLI flag name.

Probably, if a tool generates to stdout by default, it is good the tool has `--output` flag.
However, `license-generator` aims to generate `LICENSE` file.
So, this tool's main purpose is the opposite of that behavior.

Maybe, We need to add `--output` flag.

```
Options:
  --author input author name
  --project input project name that is required by some license
  --year input license year 
  --output path to output. Default: ./LICENSE
```

Output stdout:

```
license-generate --output /dev/stdout
```

**Comment by yu-ichiro** [comment]
I think that's agreeable.
Can I write a PR for this?

**Comment by azu** [comment]
Yes! Welcome to PR!
