### ISSUE TITLE
Cannot generate AGPL

### ISSUE THREAD

**Issue by Coro365** [azu/license-generator#18]
It is supposed to be AGPL (GNU Affero General Public License), but it is APGL. 
https://github.com/azu/license-generator/blob/e5456aad0fdbc97d0d1cca1e9af2df7492cb076f/src/lib.rs#L27

Therefore, the following command fails to generate it.

```
license-generator --author <name> AGPL
Not found match license: AGPL
```

Thank you!

**Comment by azu** [comment]
Thanks for finding this error, a PR is welcome!
