### ISSUE TITLE
GitHub does not identify GNU-based licenses

### ISSUE THREAD

**Issue by Coro365** [azu/license-generator#20]
When you select a GNU-based license, GitHub does not identify the license type due to the following wording.

https://github.com/azu/license-generator/blob/2efa1d60f31520e1d80939442a651220a643d988/files/gpl-3.0.txt#L3-L10

GitHub seems to recognize the license type if the license name is on the first line.
But ignores blank lines and lines containing `Copyright`, `(C)` or ` C `.  
I don't think removing the above text will affect the license itself.  
But there is no proof.

Thank you!

**Comment by azu** [comment]
I agree with you.

GPU License via GitHub does not have first copyright lines.
<img width="813" alt="image" src="https://user-images.githubusercontent.com/19714/217161039-d4459074-3ffa-465b-8125-cd7c70b2834f.png">
https://github.com/azu/gpl-licence-example/blob/main/LICENSE


We should remove these lines.
https://github.com/azu/license-generator/blob/2efa1d60f31520e1d80939442a651220a643d988/files/gpl-3.0.txt#L1-L11

**Comment by Coro365** [comment]
The license file on the GNU website also did not contain a license notice.
https://www.gnu.org/licenses/gpl-3.0.txt

Copyright and  license notice should be included in the README and each source code file, and is probably not necessary in the license file.
https://www.gnu.org/licenses/gpl-howto.en.html#license-notices

We will send you a PR later.
Thank you.

**Comment by azu** [comment]
fixed in #21 

Thanks!
